### ISSUE TITLE
Request adding get_confirmed_transaction_with_config

### ISSUE THREAD

**Issue by Jay54520** [michaelhly/solana-py#97] opened 2021-09-11 06:35 UTC
I want to know whether a transaction succeeds in 1 confirmation but `get_confirmed_transaction` will wait about 19 seconds for about 25 confirmations.

> Because `get_confirmed_transaction` returns transactions at the finalized commitment level by default (due to historical reasons).
> We recently added a [get_confirmed_transaction_with_config](https://github.com/solana-labs/solana/blob/21f4606212bcb2c61c9786374db81b448b577044/client/src/rpc_client.rs#L2554) method, and through the config struct you can request CommitmentConfig::confirmed() [2] instead of the default of CommitmentConfig::finalized()  

from mvines core contributor of solana

**Comment by kevinheavey** [comment] 2022-10-14 16:09
Closed as `getConfirmedTransaction` has since been deprecated

**Closed by kevinheavey** 2022-10-14 16:09 UTC
